apiVersion: networking.k8s.io/v1
kind: IngressClass
metadata:
  name: nginx
  annotations:
    ingressclass.kubernetes.io/is-default-class: "true"
spec:
  controller: k8s.io/ingress-nginx
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ui-service-ingress
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-staging"
spec:
  ingressClassName: nginx
  rules:
  - host: arcussmarthome.com
    http:
      paths:
      - path: /
        pathType: Prefix  # `pathType` is required in Kubernetes v1 Ingress
        backend:
          service:
            name: ui-server-service
            port:
              number: 80
      - path: /ivr
        pathType: Prefix  # `pathType` is required in Kubernetes v1 Ingress
        backend:
          service:
            name: ivr-callback-server-service
            port:
              number: 80
  - host: static.arcussmarthome.com
    http:
      paths:
      - path: /
        pathType: Prefix  # `pathType` is required in Kubernetes v1 Ingress
        backend:
          service:
            name: static-server-service
            port:
              number: 80
  - host: client.arcussmarthome.com
    http:
      paths:
      - path: /
        pathType: Prefix  # `pathType` is required in Kubernetes v1 Ingress
        backend:
          service:
            name: client-bridge-service
            port:
              number: 80
  - host: api.arcussmarthome.com
    http:
      paths:
      - path: /
        pathType: Prefix  # `pathType` is required in Kubernetes v1 Ingress
        backend:
          service:
            name: api-bridge-service
            port:
              number: 80
  - host: admin.arcussmarthome.com
    http:
      paths:
      - path: /
        pathType: Prefix  # `pathType` is required in Kubernetes v1 Ingress
        backend:
          service:
            name: grafana-service
            port:
              number: 3000
  tls:
  - secretName: nginx-staging-tls
    hosts:
    - arcussmarthome.com
    - api.arcussmarthome.com
    - client.arcussmarthome.com
    - hub.arcussmarthome.com
    - admin.arcussmarthome.com
    - static.arcussmarthome.com

