apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: alarm-service
  name: alarm-service
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alarm-service
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: alarm-service
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx64m -Dlogback.configurationFile=/config/logback.xml"
        - name: BILLING_CLIENT
          value: "noop"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        ports:
        - containerPort: 9100
          name: tcp-9100
        image: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/alarm-service:2019.10.0
        imagePullPolicy: IfNotPresent
        name: alarm-service
        volumeMounts:
          - mountPath: /config
            name: config
        livenessProbe:
          tcpSocket:
            port: 9008
          initialDelaySeconds: 15
          periodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: extrafiles
            items:
              - key: logback.xml
                path: logback.xml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: alarm-service
  name: alarm-service
spec:
  clusterIP: None
  ports:
  - port: 9100
    name: metrics
    protocol: TCP
    targetPort: 9100
  selector:
    app: alarm-service
  sessionAffinity: None
