apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: client-bridge
  name: client-bridge
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client-bridge
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: client-bridge
    spec:
      containers:
      - envFrom:
        - configMapRef:
            name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx192m -Dlogback.configurationFile=/config/logback.xml"
        - name: PARTITION_MEMBERS
          valueFrom:
            configMapKeyRef:
              key: BRIDGE_INSTANCES
              name: arcus-config
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_CLIENT
          value: 'noop'
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: SMARTY_AUTH_ID
          valueFrom:
            secretKeyRef:
              key: smarty.auth.id
              name: shared
        - name: SMARTY_AUTH_TOKEN
          valueFrom:
            secretKeyRef:
              key: smarty.auth.token
              name: shared
        - name: BILLING_PUBLIC_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.public.api.key
              name: shared
        - name: BOUNCE_HELP_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_HELP_URL
              name: arcus-config
        - name: BOUNCE_APPLE_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_APPLE_URL
              name: arcus-config
        - name: BOUNCE_APPLE_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_APP_URL
              name: arcus-config
        - name: BOUNCE_APP_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_APP_URL
              name: arcus-config
        - name: BOUNCE_ANDROID_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_ANDROID_URL
              name: arcus-config
        - name: BOUNCE_WEB_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_WEB_URL
              name: arcus-config
        - name: BOUNCE_REDIRECT_URL
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_REDIRECT_URL
              name: arcus-config
        - name: REDIRECT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: REDIRECT_BASE_URL
              name: arcus-config
        - name: IOS_APP_IDS
          valueFrom:
            configMapKeyRef:
              key: BOUNCE_IOS_APP_IDS
              name: arcus-config
        - name: VIDEO_PREVIEW_UPLOAD_URL
          valueFrom:
            configMapKeyRef:
              key: VIDEO_PREVIEW_UPLOAD_URL
              name: arcus-config
        - name: SECURE_STATIC_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL
              name: arcus-config
        - name: INVOICE_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: INVOICE_RESOURCE_BASE_URL
              name: arcus-config
        - name: STATIC_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL # only secure, no http
              name: arcus-config
        - name: CAMERA_PREVIEW_BASEURL
          valueFrom:
            configMapKeyRef:
              key: CAMERA_PREVIEW_BASEURL
              name: arcus-config
        - name: CORS_ORIGINS
          valueFrom:
            configMapKeyRef:
              key: CORS_ORIGINS
              name: arcus-config
        - name: DEFAULT_SERVICE_LEVEL
          valueFrom:
            configMapKeyRef:
              key: DEFAULT_SERVICE_LEVEL
              name: arcus-config
        image: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/client-bridge:2019.10.0
        imagePullPolicy: Always
        name: client-bridge
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "50m"
        volumeMounts:
         - mountPath: /config
           name: config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: config
        configMap:
          name: extrafiles
          items:
          - key: logback.xml
            path: logback.xml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: client-bridge
  name: client-bridge
spec:
  clusterIP: None
  ports:
  - port: 9100
    name: metrics
    protocol: TCP
    targetPort: 9100
  selector:
    app: client-bridge
  sessionAffinity: None
