apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ivr-callback-server
  name: ivr-callback-server
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: ivr-callback-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ivr-callback-server
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m -Dlogback.configurationFile=/config/logback.xml"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: TLS_SERVER
          value: "false"
        - name: USE_SSL
          value: "false"
        - name: TWILIO_ACCOUNT_AUTH
          valueFrom:
            secretKeyRef:
              key: twilio.account.auth
              name: shared
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              key: twilio.account.sid
              name: shared
        - name: TWILIO_ACCOUNT_FROM
          valueFrom:
            secretKeyRef:
              key: twilio.account.from
              name: shared
        - name: TWILIO_CALLBACK_HOST
          valueFrom:
            configMapKeyRef:
              key: TWILIO_CALLBACK_HOST
              name: arcus-config
        image: ghcr.io/wl-net/arcusplatform/arcus-ivr-callback-server:2019.10.0
        imagePullPolicy: IfNotPresent
        name: ivr-callback-server
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "100m"
            memory: "128Mi"
        volumeMounts:
          - mountPath: /config
            name: config
        readinessProbe:
          tcpSocket:
            port: 9100
          initialDelaySeconds: 15
          periodSeconds: 10
        livenessProbe:
          tcpSocket:
            port: 9100
          initialDelaySeconds: 30
          periodSeconds: 60
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
        - name: config
          configMap:
            name: extrafiles
            items:
              - key: logback.xml
                path: logback.xml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: ivr-callback-server
  name: ivr-callback-server
spec:
  externalTrafficPolicy: Cluster
  ports:
    - port: 9100
      name: metrics
      protocol: TCP
      targetPort: 9100
  selector:
    app: ivr-callback-server
  sessionAffinity: None
  type: NodePort
