apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: notification-services
  name: notification-services
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: notification-services
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: notification-services
    spec:
      containers:
      - envFrom:
          - configMapRef:
              name: cluster-config
        env:
        - name: JAVA_OPTS
          value: "-Xms64m -Xmx128m -Dlogback.configurationFile=/config/logback.xml"
        - name: BILLING_URL
          valueFrom:
            configMapKeyRef:
              key: BILLING_URL
              name: arcus-config
        - name: BILLING_API_KEY
          valueFrom:
            secretKeyRef:
              key: billing.api.key
              name: shared
        - name: IRIS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: iris.aes.secret
              name: shared
        - name: IRIS_AES_IV
          valueFrom:
            secretKeyRef:
              key: iris.aes.iv
              name: shared
        - name: QUESTIONS_AES_SECRET
          valueFrom:
            secretKeyRef:
              key: questions.aes.secret
              name: shared
        - name: REDIRECT_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: REDIRECT_BASE_URL
              name: arcus-config
        - name: SECURE_STATIC_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL
              name: arcus-config
        - name: STATIC_RESOURCE_SERVER_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL
              name: arcus-config          
        - name: STATIC_RESOURCE_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: SECURE_STATIC_RESOURCE_BASE_URL # only secure, no http
              name: arcus-config
        - name: EMAIL_SENDEREMAIL
          valueFrom:
            configMapKeyRef:
              key: EMAIL_SENDEREMAIL
              name: arcus-config
        - name: EMAIL_REPLYTO
          valueFrom:
            configMapKeyRef:
              key: EMAIL_REPLYTO
              name: arcus-config
        - name: WEBHOME_BASE_URL
          valueFrom:
            configMapKeyRef:
              key: WEBHOME_BASE_URL
              name: arcus-config
        - name: TWILIO_CALLBACK_SERVERURL
          valueFrom:
            configMapKeyRef:
              key: TWILIO_CALLBACK_SERVERURL
              name: arcus-config
        - name: NOTIFICATIONSERVICE_SENDER_EMAIL
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONSERVICE_SENDER_EMAIL
              name: arcus-config
        - name: NOTIFICATIONSERVICE_SENDER_APNS
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONSERVICE_SENDER_APNS
              name: arcus-config
        - name: NOTIFICATIONSERVICE_SENDER_GCM
          valueFrom:
            configMapKeyRef:
              key: NOTIFICATIONSERVICE_SENDER_GCM
              name: arcus-config
        - name: APNS_TOPIC
          valueFrom:
            configMapKeyRef:
              key: APNS_TOPIC
              name: arcus-config
        - name: MAILGUNEMAIL_PROVIDER_APIKEY
          valueFrom:
            secretKeyRef:
              key: mailgunemail.provider.apikey
              name: shared
        - name: EMAIL_PROVIDER_APIKEY
          valueFrom:
            secretKeyRef:
              key: email.provider.apikey
              name: shared
        - name: EMAIL_PROVIDER_DOMAIN
          valueFrom:
            secretKeyRef:
              key: email.provider.domain
              name: shared
        - name: TWILIO_ACCOUNT_AUTH
          valueFrom:
            secretKeyRef:
              key: twilio.account.auth
              name: shared
        - name: TWILIO_ACCOUNT_SID
          valueFrom:
            secretKeyRef:
              key: twilio.account.sid
              name: shared
        - name: TWILIO_ACCOUNT_FROM
          valueFrom:
            secretKeyRef:
              key: twilio.account.from
              name: shared
        - name: TWITTER_UNAME
          value: IrisByLowes
        - name: APNS_PKCS12_PATH
          value: /data/secrets/apns.pfx
        - name: APNS_PKCS12_PASSWORD
          valueFrom:
            secretKeyRef:
              key: apns.pkcs12.password
              name: shared
        image: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/notification-services:2019.10.0
        imagePullPolicy: IfNotPresent
        name: notification-services
        resources:
          limits:
            cpu: "1"
          requests:
            cpu: "50m"
        volumeMounts:
        - name: data-secrets
          mountPath: "/data/secrets"
        - name: config
          mountPath: /config
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
          tcpSocket:
            port: 9002
          initialDelaySeconds: 15
          periodSeconds: 60
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: data-secrets
        secret:
          secretName: shared
          items:
          - key: apns.pfx
            path: apns.pfx
      - name: config
        configMap:
          name: extrafiles
          items:
          - key: logback.xml
            path: logback.xml
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: notification-services
  name: notification-services
spec:
  externalTrafficPolicy: Cluster
  ports:
  - port: 9100
    name: metrics
    protocol: TCP
    targetPort: 9100
  selector:
    app: notification-services
  sessionAffinity: None
  type: NodePort
