apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui-server
  name: ui-server
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: ui-server
    spec:
      containers:
      - image: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/ui-server:latest
        imagePullPolicy: Always
        name: ui-server
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        env:
        - name: ARCUS_WS_URI
          valueFrom:
            configMapKeyRef:
              key: ARCUS_WS_URI
              name: arcus-config
        - name: ARCUS_HTTP_URI
          valueFrom:
            configMapKeyRef:
              key: ARCUS_HTTP_URI
              name: arcus-config
        - name: ARCUS_ENABLE_HUB_WIFI_SCAN
          valueFrom:
            configMapKeyRef:
              key: ARCUS_ENABLE_HUB_WIFI_SCAN
              name: arcus-config
        - name: ARCUS_ENABLE_BATTERY_PERCENTAGE
          valueFrom:
            configMapKeyRef:
              key: ARCUS_ENABLE_BATTERY_PERCENTAGE
              name: arcus-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
