# Edit this file to customize Arcus configuration for this deployment.
# Changes here are preserved across 'arcuscmd apply' runs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: arcus-config
  namespace: default
data:
  BRIDGE_INSTANCES: "1"
  NOTIFICATIONSERVICE_SENDER_APNS: noop
  NOTIFICATIONSERVICE_SENDER_GCM: noop
