# Edit this file to customize Cassandra/Kafka configuration for this deployment.
# Changes here are preserved across 'arcuscmd apply' runs.
apiVersion: v1
kind: ConfigMap
metadata:
  name: cluster-config
  namespace: default
data:
  BOOTSTRAP_SERVERS: 192.168.1.14:9092
  CLUSTER_SERVICE_DAO: cassandra
  CLUSTER_ZK_HOST: 192.168.1.13:2181
  cassandra_history_contactPoints: 192.168.1.10
  cassandra_contactPoints: 192.168.1.10
  CASSANDRA_CONTACTPOINTS: 192.168.1.10
  CASSANDRA_KEYSPACE: dev
  CASSANDRA_LOADBALANCINGPOLICY: roundrobin
  ZOOKEEPER: 192.168.1.13:2181
  ZOOKEEPEROPS: 192.168.1.13:2181
  METRICS_TOPIC_ENABLED: 'true'
  KAFKA_COMPRESSION_TYPE: gzip
  KAFKA_CLIENT_RACK: 'dc1'
