resources:
- ../../config
- cassandra.yaml
- kafka.yaml
- zookeeper.yaml
- grafana.yaml
patches:
- path: cert-provider.yaml
- path: shared-config.yaml
- path: ui-service-ingress.yaml
- path: arcus-config-tunable.yaml
- path: cluster-config-tunable.yaml
- target:
    kind: Deployment
  path: image-pull-policy.yaml

images:
- name: ghcr.io/wl-net/arcusplatform/arcus-alarm-service
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/alarm-service
- name: ghcr.io/wl-net/arcusplatform/arcus-client-bridge
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/client-bridge
- name: ghcr.io/wl-net/arcusplatform/arcus-driver-services
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/driver-services
- name: ghcr.io/wl-net/arcusplatform/arcus-history-service
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/history-service
- name: ghcr.io/wl-net/arcusplatform/arcus-hub-bridge
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/hub-bridge
- name: ghcr.io/wl-net/arcusplatform/arcus-ivr-callback-server
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/ivr-callback-server
- name: ghcr.io/wl-net/arcusplatform/arcus-notification-services
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/notification-services
- name: ghcr.io/wl-net/arcusplatform/arcus-platform-services
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/platform-services
- name: ghcr.io/wl-net/arcusplatform/arcus-rule-service
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/rule-service
- name: ghcr.io/wl-net/arcusplatform/arcus-scheduler-service
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/scheduler-service
- name: ghcr.io/wl-net/arcusplatform/arcus-subsystem-service
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/subsystem-service
- name: ghcr.io/wl-net/arcusplatform/arcus-modelmanager
  newName: us-west1-docker.pkg.dev/arcus-238802/arcus-prod/arcus/modelmanager
