resources:
- ../../config
- cassandra.yaml
- kafka.yaml
- zookeeper.yaml
- grafana.yaml
patches:
- path: cert-provider.yaml
- path: shared-config.yaml
- path: ui-service-ingress.yaml
- path: arcus-config-tunable.yaml
- path: cluster-config-tunable.yaml
- target:
    kind: Deployment
  path: image-pull-policy.yaml
