bases:
- ../../config
patchesStrategicMerge:
- cert-provider.yaml
- shared-config.yaml
- ui-service-ingress.yml
- arcus-config-tunable.yml
- cluster-config-tunable.yml

resources:
- cassandra.yaml
- kafka.yaml
