resources:
- ../../config
- cassandra.yaml
- kafka.yaml
- zookeeper.yml
patches:
- path: cert-provider.yaml
- path: shared-config.yaml
- path: ui-service-ingress.yml
- path: arcus-config-tunable.yml
- path: cluster-config-tunable.yml
- target:
    kind: Deployment
  path: image-pull-policy.yml
