resources:
- ../../config
patches:
- path: cert-provider.yaml
- path: shared-config.yaml
- path: ui-service-ingress.yaml
- path: cluster-config.yaml
- path: arcus-config-tunable.yaml
- path: cluster-config-tunable.yaml
